# Generated by Django 6.0.2 on 2026-03-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
